# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
#Ali Alkadhim

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(258, 264)
        MainWindow.setMinimumSize(QtCore.QSize(258, 264))
        MainWindow.setMaximumSize(QtCore.QSize(258, 264))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.label.setObjectName("label")
        self.id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.id.setGeometry(QtCore.QRect(80, 40, 113, 20))
        self.id.setObjectName("id")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_2.setObjectName("label_2")
        self.john = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.john.setGeometry(QtCore.QRect(30, 120, 62, 14))
        self.john.setObjectName("john")
        self.candidates = QtWidgets.QButtonGroup(MainWindow)
        self.candidates.setObjectName("candidates")
        self.candidates.addButton(self.john)
        self.joe = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.joe.setGeometry(QtCore.QRect(110, 120, 62, 14))
        self.joe.setObjectName("joe")
        self.candidates.addButton(self.joe)
        self.jane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.jane.setGeometry(QtCore.QRect(200, 120, 62, 14))
        self.jane.setObjectName("jane")
        self.candidates.addButton(self.jane)
        self.button_vote = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_vote.setGeometry(QtCore.QRect(100, 160, 56, 17))
        self.button_vote.setObjectName("button_vote")
        self.label_message = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_message.setGeometry(QtCore.QRect(30, 190, 211, 20))
        self.label_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_message.setObjectName("label_message")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 258, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Student Body President"))
        self.label.setText(_translate("MainWindow", "Student ID"))
        self.label_2.setText(_translate("MainWindow", "Candidates:"))
        self.john.setText(_translate("MainWindow", "John"))
        self.joe.setText(_translate("MainWindow", "Joe"))
        self.jane.setText(_translate("MainWindow", "Jane"))
        self.button_vote.setText(_translate("MainWindow", "Vote!"))
        self.label_message.setText(_translate("MainWindow", "Enter student ID and select candidate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
